version: "3.9"
services:
  postgres:
    image: postgres:14.2
    container_name: postgres_container
    environment:
      POSTGRES_DB: "Schedule"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - schedule
  schedule:
    image: ubik33/schedule
    container_name: schedule_server
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/Schedule"
    ports:
      - "8082:8082"
    networks:
      - schedule

networks:
  schedule:
    driver: bridge
